@RiverBooks.Web_HostAddress = http://localhost:5160


GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json

###

@BookId=e2c8eca2-9382-4fbc-88ea-d5a09cea4e94
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/book
Accept: application/json
Content-Type: application/json

{
      "title": "The Saga of Lich King",
      "author": "Blizzard",
      "price": 23.90
}

###
DELETE {{RiverBooks.Web_HostAddress}}/books/2c1597e8-ab67-4b88-ba67-04de4c5df8cd
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/books/4040756b-9770-46ad-923b-a5c524f4de85/pricehistory
Accept: application/json
Content-Type: application/json

{
      "id" : "4040756b-9770-46ad-923b-a5c524f4de85",
      "price": -9.99
}

###
POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
      "email" : "jack.michael@test.com",
      "password" : "P@ssword1",
      "fullname" : "Jack Michael"
}

###

POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
      "email" : "danish.junaid@test.com",
      "password" : "P@ssword1"
}

###
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJkYW5pc2guanVuYWlkQHRlc3QuY29tIiwiaWF0IjoxNzIxODgxNjA3LCJleHAiOjE3MjE4ODUyMDcsIm5iZiI6MTcyMTg4MTYwN30.40zAInZcnMKbOcbVV7lIyzQVZ-lNpFx8n2wDMjW81f8


###
GET {{RiverBooks.Web_HostAddress}}/users
Accept: application/json

###
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId" : "2219fac9-7fd0-46d9-9944-511660a9b764",
  "quantity" : 1
}

###

GET {{RiverBooks.Web_HostAddress}}/cart      
Accept: application/json
Authorization: Bearer {{token}}